### ISSUE TITLE
Is S06A supported?

### ISSUE THREAD

**Issue by advphp** [jackyes/GoLiveTracking#1]
Hello

Is S06A device supported?

**Comment by jackyes** [comment]
Unfortunately, I am not familiar with the S06A device. However, if it is capable of sending requests to custom external servers, it is likely compatible. Essentially, it is sufficient to initiate a request from the device like the following:

`http(s)://[address]:[port]/addpoint?lon=[LON]&lat=[LAT]&timestamp=[UNIXTIMESTAMP]&altitude=[ALT]&speed=[SPEED]&bearing=[BEARING]&user=[USERNR]&session=[SESSIONNR]&key=[KEY]`

Note:  not all parm are mandatory

(replacing the values in the [] brackets with the correct values ;))
